config/routes.rb
require "resque_web"

Main::Application.routes.draw do

  
  
  ActiveAdmin.routes(self)
  
  
  ResqueWeb::Engine.eager_load!

  mount ResqueWeb::Engine => "/resque_web"

  get "users/leadboard"
  get "users/signin_popup"

  get "splash/index", as: :splash
  root to: "contests#browse"

  get "terms/", :controller => "terms", :action => "index"
  get "privacy-policy/", :controller => "privacy_policy", :action => "index"

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations' }

  get '/users/subregion_options' => 'users#subregion_options'
  resources :pages do
    collection do
      get :rules_faq
    end
  end
  resources :entries do
    member do
        post 'admin'
    end
  end

  scope(:path => 'admin', :as => 'admin') do
    get 'games', to: 'admin#games'
    get 'entries', to: 'admin#entries'
    get 'contests', to: 'admin#contests'
    get 'users', to: 'admin#users'
    get "/", to: "admin#index"
  end

  resources :lineups do
    member do
      get :export
    end
    resource :entries
  end
  resources :players, only: [] do
    member do
      get :stats
    end
  end
  resources :contests, only: [:index, :show] do
    collection do
      get 'browse'
    end
  end

  resources :waiting_lists, only: [:new, :create, :show] do
    collection do
      get :invite
      post :inviting
    end
  end

  resources :accounts, only: [:create, :edit, :show, :index] do
    collection do
      get :new_cc
      get :profile
      get :history
      get :withdraw
      get :add_fund

      resources :credit_cards
      post 'credit_cards/deposit' => 'credit_cards#deposit'

      get 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal', :as => :withdrawal
      post 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal_post'
      resources :bank_accounts
    end
  end

   resources :projections do
     collection do
       get "with_stats/:sport_name" => 'projections#with_stats'
       get "stats_by_game/:sport_name" => 'projections#stats_by_game', :as => :stats_by_game
       get ":sport_name" => 'projections#index' # funky, index has a parameter? does this work?
     end
     resources :projection_by_stats do
       resources :projection_by_stat_and_games do
         resources :projection_breakdowns
       end
     end
   end

  resources :password_resets

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/admin/contests.html.erb
<div>
  <div class="clear">&nbsp;</div>

  <div class="filter_row">
    <div class="row">
      <div class="col-md-4">
        <h4>Contests</h4>
      </div>
      <div class="col-md-8">
        <!--<span class="green"><a href="#">Join More Contest »</a></span>-->
        <!--<span class="green"><%= link_to 'View my Lineups', lineups_path %></span>-->
      </div>
    </div>
  </div>


  <div class="">
    <table class="table sortable">
      <thead>
      <tr>
        <th>ID</th>
        <th>Sport</th>
        <th>Contest Date</th>
        <th>Contest Type</th>
        <th>Entry Fee</th>
        <th>Prize</th>
        <th>Number of Entries</th>
        <th>Winners</th>
      </tr>
      </thead>

      <tbody>
      <% @contests.each do |contest| %>
          <tr>
            <td><%= contest.id %></td>
            <td><%= contest.contestdate %></td>
            <td><%= contest.sport %></td>
            <td><%= contest.contest_type %></td>
            <td><%= contest.entry_fee %></td>
            <td><%= contest.prizepool %></td>
            <td><%= contest.entries_count %></td>
            <td>
            <% contest.winnings.each do |win| %>

                <%= win[0].lineup.user.username %>, <%= win[1] %><br>
            <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/entries.html.erb
<div>
  <div class="clear">&nbsp;</div>

  <div class="filter_row">
    <div class="row">
      <div class="col-md-4">
        <h4>Entries</h4>
      </div>
      <div class="col-md-8">
        <!--<span class="green"><a href="#">Join More Contest »</a></span>-->
        <!--<span class="green"><%= link_to 'View my Lineups', lineups_path %></span>-->
      </div>
    </div>
  </div>


  <div class="">
    <table class="table sortable">
      <thead>
      <tr>
        <th>ID</th>
        <th data-defaultsort="desc">Contest ID</th>
        <th>Contest Date</th>
        <th>Final Entry Position</th>
        <th>Final Entry Score</th>
        <th>Game IDs</th>
      </tr>
      </thead>

      <tbody>
      <% @entries.each do |entry| %>
          <tr>
            <td><%= entry.id %></td>
            <td><%= entry.contest.id %></td>
            <td><%= entry.contest.contestdate %></td>
            <td><%= entry.final_pos %></td>
            <td><%= entry.final_score %></td>
            <td><%= entry.games.pluck(:id) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/games.html.erb
<div>
  <div class="clear">&nbsp;</div>

  <div class="filter_row">
    <div class="row">
      <div class="col-md-4">
        <h4>Games</h4>
      </div>
      <div class="col-md-8">
        <span class="green"><a href="#">Join More Contest »</a></span>
        <span class="green"><%= link_to 'View my Lineups', lineups_path %></span>
      </div>
    </div>
  </div>


  <div class="live-contests-dest">
    <table class="contestHead table sortable">
      <thead>
      <tr>
        <th>ID</th>
        <th data-defaultsort="desc">Game date</th>
        <th class="srt-live-in">Start / Ext ID</th>
        <th>Home</th>
        <th>Away</th>
        <th>Status</th>
      </tr>
      </thead>

      <tbody>
      <% @games.each do |game| %>
          <tr>
            <td><%= game.id %></td>
            <td><%= game.playdate %></td>
            <td><%= game.scheduledstart %><br><%= game.ext_game_id %></td>
            <td><%= game.home_team.teamalias %></td>
            <td><%= game.away_team.teamalias %></td>
            <td><%= game.status %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/index.html.erb
<div>

<h3>Ops Dashboards</h3>
<ul>
  <li><%= link_to 'Sidekiq', sidekiq_web_path %></li>
  <li><%= link_to 'Resque', resque_web_path %></li>

</ul>

</div>

app/views/admin/users.html.erb
<div>
  <div class="clear">&nbsp;</div>

  <div class="filter_row">
    <div class="row">
      <div class="col-md-4">
        <h4>Users</h4>
      </div>
      <div class="col-md-8">
        <span class="green"><a href="#">Join More Contest »</a></span>
        <span class="green"><%= link_to 'View my Lineups', lineups_path %></span>
      </div>
    </div>
  </div>


  <div class="live-contests-dest">
    <table class="contestHead table sortable">
      <thead>
      <tr>
        <th>Username</th>
        <th >Email</th>
        <th data-defaultsort="desc">Created at</th>
        <th>Last Login</th>
        <th>Admin?</th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= user.last_sign_in_at %></td>
            <td><%= user.created_at %></td>
            <td><%= user.admin %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>