config/routes.rb
require "resque_web"

Main::Application.routes.draw do

  
  
  ActiveAdmin.routes(self)
  
  
  ResqueWeb::Engine.eager_load!

  mount ResqueWeb::Engine => "/resque_web"

  get "users/leadboard"
  get "users/signin_popup"

  get "splash/index", as: :splash
  root to: "contests#browse"

  get "terms/", :controller => "terms", :action => "index"
  get "privacy-policy/", :controller => "privacy_policy", :action => "index"

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations' }

  get '/users/subregion_options' => 'users#subregion_options'
  resources :pages do
    collection do
      get :rules_faq
    end
  end
  resources :entries do
    member do
        post 'admin'
    end
  end

  scope(:path => 'admin', :as => 'admin') do
    get 'games', to: 'admin#games'
    get 'entries', to: 'admin#entries'
    get 'contests', to: 'admin#contests'
    get 'users', to: 'admin#users'
    get "/", to: "admin#index"
  end

  resources :lineups do
    member do
      get :export
    end
    resource :entries
  end
  resources :players, only: [] do
    member do
      get :stats
    end
  end
  resources :contests, only: [:index, :show] do
    collection do
      get 'browse'
    end
  end

  resources :waiting_lists, only: [:new, :create, :show] do
    collection do
      get :invite
      post :inviting
    end
  end

  resources :accounts, only: [:create, :edit, :show, :index] do
    collection do
      get :new_cc
      get :profile
      get :history
      get :withdraw
      get :add_fund

      resources :credit_cards
      post 'credit_cards/deposit' => 'credit_cards#deposit'

      get 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal', :as => :withdrawal
      post 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal_post'
      resources :bank_accounts
    end
  end

   resources :projections do
     collection do
       get "with_stats/:sport_name" => 'projections#with_stats'
       get "stats_by_game/:sport_name" => 'projections#stats_by_game', :as => :stats_by_game
       get ":sport_name" => 'projections#index' # funky, index has a parameter? does this work?
     end
     resources :projection_by_stats do
       resources :projection_by_stat_and_games do
         resources :projection_breakdowns
       end
     end
   end

  resources :password_resets

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_account_heading.html.erb
<br>
<h2>MY ACCOUNT</h2>
<div class="clearfix">&nbsp;</div>

<div class="light_grey paymenttab grey_bottom_border">
  <ul class="list-inline">
    <li>
      <%= link_to profile_accounts_path do %>
          <span class="green active">Account Information »</span>
      <%end%>
    </li>
    <li>
      <%= link_to history_accounts_path do %>
          <span class="green">Account History »</span>
      <%end%>
    </li>
    <li>
      <%= link_to withdraw_accounts_path do %>
          <span class="green">Withdrawal Request »</span>
      <%end%>
    </li>
    <li>
      <%= link_to new_bank_account_path do %>
          <span class="green">Add Bank Account Request »</span>
      <%end%>
    </li>
    <li class="pull-right">
      <a href="#"><%= image_tag "questionmark.png", alt: "Question Mark" %></a>
    </li>
  </ul>
</div>
<div class="clearfix">&nbsp;</div>

app/views/shared/_footer.html.erb
<footer>
  <div class='footerContainer container'>

    <div class='row logo-row'>
      <%= image_tag 'main_logo.png',  alt: "Fantasy capital logo" %>
    </div>

    <div class='row'>
      <div class='col-md-7'>
        <ul class='company-section'>
          <li class="item-header">Company</li>
          <li>
            <a href="#">Home</a>
          </li>
          <li>
            <a href="mailto:support@fantasycapital.com">Contact Us</a>
          </li>
          <li>
            <a href="/terms">Terms</a>
          </li>
          <li>
            <a href="/privacy-policy">Privacy</a>
          </li>
        </ul>
        <!--
        <ul class="support-section">
          <li class="item-header">Support</li>
          <li>
            <a href="#">100% Legal</a>
          </li>
          <li>
            <a href="#">Affiliates</a>
          </li>
          <li>
            <a href="#">Deposit Bonus</a>
          </li>
          <li>
            <a href="#">Careers</a>
          </li>
        </ul>
        -->
        <ul class="contact-section">
          <li class="item-header">Connect With Us</li>
          <li class="social-links">
            <%= link_to 'https://www.facebook.com/fantasycapital' do %>
              <%= image_tag 'square_facebook.png', alt: 'Fantasy Capital Facebook page' %>
            <% end %>
            <%= link_to 'https://twitter.com/fantasycapital' do %>
              <%= image_tag 'square_twitter.png', alt: 'Fantasy Capital Twitter page' %>
            <% end %>
            <br />
            <%= link_to 'https://plus.google.com/u/0/113355143365224061494/about' do %>
              <%= image_tag 'square_gplus.png', alt: 'Fantasy Capital Google Plus page' %>
            <% end %>

          </li>
        </ul>
      </div>

      <div class='col-md-5'>
        <ul class="partners-section">
          <li class="item-header">Partners</li>
          <li class="partner-links">
            <a href="#">
              <%= image_tag 'stripe.png', :height => 20 %>
            </a>
            <a href="#">
              <%= image_tag 'sports_data.png', :height => 20 %>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<%= render 'shared/topbar' %>

<header>
  <div class='container'>
    <h1 class='logo'>
      <%= link_to root_path do%>
        <%= image_tag 'main_logo.png', alt: 'Fantasy Capital' %>
        <em>Daily Fantasy Sports</em>
       <% end %>
    </h1>

    <% if current_user %>
      <div class='balanceBlock'>
        <div class="top-border"></div>
        <strong>Your Balance</strong>
        <strong class='ajax-modal pull-right' id='add-fund' data-url="<%= add_fund_accounts_path %>">
          Add Funds
          <i class="glyphicon glyphicon-plus"></i>
        </strong>
        <h1>
          <sup>$</sup>
          <%= number_to_currency(current_user.account_balance, unit: '') %>
        </h1>
      </div>
    <% end %>

    <div style="clear:both;"></div>
    <div class='navbar navbar-default capitalnavbar' role="navigation">
      <div class='navbar-header'>
        <button class='navbar-toggle' data-target=".mainMenu" data-toggle="collapse" type="button">
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
      <div class='navbar-collapse collapse mainMenu'>
        <ul class='nav navbar-nav'>
          <li class='<%= menu_classes 'home' %>'>
            <div class="padding">
              <%= link_to 'Home', root_path %>
              <div class="line"></div>
            </div>
            <div class="arrow-down"></div>
          </li>
          <li class='<%= menu_classes 'entries' %>'>
            <div class="padding">
              <%= link_to 'Entries', entries_path, :class => ("require-signin" unless user_signed_in?) %>
              <div class="line"></div>
            </div>
          </li>
          <!--
          <li class='<%= menu_classes 'lineups' %>'>
            <div class="padding">
              <%= link_to 'Lineups', lineups_path, :class => ("require-signin" unless user_signed_in?) %>
              <div class="line"></div>
            </div>
          </li>
          <li class='<%= menu_classes 'leaderboard' %>'>
            <div class="padding">
              <%= link_to 'Leaderboard', users_leadboard_path, :class => ("require-signin" unless user_signed_in?) %>
              <div class="line"></div>
            </div>
          </li>
          -->
          <li class='<%= menu_classes 'rules' %>'>
            <div class="padding">
              <%= link_to 'Rules/Faq', rules_faq_pages_path, :class => ("require-signin" unless user_signed_in?) %>
              <div class="line"></div>
            </div>
          </li>
          <li class='<%= menu_classes 'account' %>'>
            <div class="padding">
              <%= link_to 'Account', profile_accounts_path, :class => ("require-signin" unless user_signed_in?) %>
              <div class="line"></div>
            </div>
          </li>
          <li class="welcome-box">
            <% if user_signed_in? %>
            <div class="welcome-text">
              <a href="javascript:void(0)">
                Welcome, <span class="first-name"><%= current_user.username%></span>
              </a>
            </div>

            <ul class="usermenu">
              <li>
                <a href="/users/sign_out" data-method="delete" class="sign-out">
                  Log Out
                </a>
              </li>
            </ul>
            <% else %>
              <!--<%= link_to "SIGN UP" , new_user_registration_path, :class => 'link' %>
              <a href="#" class="link">/</a>
              <%= link_to "SIGN IN" , new_user_session_path, :class => 'link' %>
              <span class="arrow">&#10095;</span>-->
              <%= link_to "JOIN NOW" , '/', :class => 'link require-signin' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_player_stats.html.erb
  <% stats = PlayerStat::STATS_ALLOWED.keys %>
  <div class="capitalcontent">
    <div class="capitalpopup">
      <div class="popupTitle">
        <h2><%= @player.name %> &nbsp; </h2>
        <h3><%= @player.team %>#<%= @player.sport_position.name %></h3>
        <h3>Salary:</h3>
        <h4><%= number_to_currency @player.salary.to_i, precision: 0 %></h4>
        <button type="button" class="btnClose" data-dismiss="modal">X</button>
      </div>
      <h3>Next Gm:</h3>
      <h4>Ten @Den (12/08 4:05 PM EST)</h4>
      <!--<div class="draftPlayer">DRAFT PLAYER</div>-->
      <%= content_tag :div, class: 'draftPlayer', data: {dismiss: 'modal', player_id: @player.id, player_name: @player.name, player_salary: @player.salary, player_opp: 'Ind@SDD', player_fppg: 24.5, player_position: @player.sport_position.name} do %>
        DRAFT PLAYER
      <% end %>

      <div class="clear">&nbsp;</div>
      <div>
        <ul class="nav nav-tabs" id="filterSport">
          <li class="active"><a href="#SUMMARY" data-toggle="tab">SUMMARY</a></li>
          <li><a href="#MATCHUP" data-toggle="tab">MATCHUP</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="SUMMARY">
            <table width="713" class="summarymatchup">
              <thead>
                <tr>
                  <th width="180"></th>
                <% stats.each do |v| %>
                  <th width="100"><%= v %></th>
                <% end %>
                </tr>
              </thead>
              <tbody>
                <% @summary.each do |key, stat_line| %>
                  <tr>
                    <td><%= key %></td>
                  <% stats.each do |v| %>
                    <th><%= number_with_precision(stat_line[v], precision: 2) %></th>
                  <% end %>
                  </tr>
                <% end %>
                
              </tbody>
            </table>
          </div>
          <div class="tab-pane" id="MATCHUP">
            <table width="713" class="summarymatchup">
              <thead>
                <tr>
                  <th width="180">G</th>
                <% stats.each do |v| %>
                  <th width="100"><%= v %></th>
                <% end %>
                </tr>
              </thead>
              <tbody>
                <% @matchup.each do |key, stat_line| %>
                  <tr>
                    <td><%= key %></td>
                  <% stats.each do |v| %>
                    <th><%= number_with_precision(stat_line[v], precision: 2) %></th>
                  <% end %>
                  </tr>
                <% end %>
                
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <br/>
      <h2>LATEST PLAYER NEWS</h2>
      <div class="clear">&nbsp;</div>
      <p><strong>Dec 4</strong>: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
      <p><strong>Dec 4</strong>: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
    </div>
  </div>

  <script>
    // BUGBUG: This is broken (need page:load signal for turbolinks). Also, what does it do??

    // a click does another click, it's a workaround
    // call should be used instead with a node as this parameter
    // somefunction.call($(".something")[0])
    // this should be investigated and reworked if possible as 
    // inline scripts cause maintenance issues in js
    $(document).on("ready page:load", function (){
      $('.draftPlayer').on("click", function () {
        $('#player_<%= @player.id %> .add-to-lineup').first().click();
      });
      
    });
  </script>

app/views/shared/_topbar.html.erb
<div class='topbarWraper'>
  <div class='navbar navbar-default navbar-static-top capital_top_nav topbar-nav' role="navigation">
    <div class='container'>
      <!--<div class='navbar-header'>
        <button class='navbar-toggle' data-target=".capitalcollapse" data-toggle="collapse" type="button">
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>-->
      <% if current_user.try(:admin?)%>
      <div class="" style="position:absolute; top:10px; left:10px; z-index:9999">
        <%= link_to 'Admin', admin_path %>
      </div>
      <% end %>
      <div class=''>
        <ul class='nav navbar-nav navbar-nav-centered clearfix'>
          <li>
            <a href="#" class="pull-left">
              <strong class="learn-more">Learn more about Fantasy Capital</strong>
              <div class="learn-more-img"> 
                <img class="no-margin" src="<%= image_path('header-learnmore-video.jpg') %>" width="40" height="22"> 
              </div>
            </a>
            <%= link_to invite_waiting_lists_path, class: 'refer-link pull-right' do%>
              <strong class='ajax-modal refer-friends'>Refer Friends for Cash &rarr;</strong>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
    <div class="header-close-button"></div>
  </div>
</div>