config/routes.rb
require "resque_web"

Main::Application.routes.draw do

  
  
  ActiveAdmin.routes(self)
  
  
  ResqueWeb::Engine.eager_load!

  mount ResqueWeb::Engine => "/resque_web"

  get "users/leadboard"
  get "users/signin_popup"

  get "splash/index", as: :splash
  root to: "contests#browse"

  get "terms/", :controller => "terms", :action => "index"
  get "privacy-policy/", :controller => "privacy_policy", :action => "index"

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations' }

  get '/users/subregion_options' => 'users#subregion_options'
  resources :pages do
    collection do
      get :rules_faq
    end
  end
  resources :entries do
    member do
        post 'admin'
    end
  end

  scope(:path => 'admin', :as => 'admin') do
    get 'games', to: 'admin#games'
    get 'entries', to: 'admin#entries'
    get 'contests', to: 'admin#contests'
    get 'users', to: 'admin#users'
    get "/", to: "admin#index"
  end

  resources :lineups do
    member do
      get :export
    end
    resource :entries
  end
  resources :players, only: [] do
    member do
      get :stats
    end
  end
  resources :contests, only: [:index, :show] do
    collection do
      get 'browse'
    end
  end

  resources :waiting_lists, only: [:new, :create, :show] do
    collection do
      get :invite
      post :inviting
    end
  end

  resources :accounts, only: [:create, :edit, :show, :index] do
    collection do
      get :new_cc
      get :profile
      get :history
      get :withdraw
      get :add_fund

      resources :credit_cards
      post 'credit_cards/deposit' => 'credit_cards#deposit'

      get 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal', :as => :withdrawal
      post 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal_post'
      resources :bank_accounts
    end
  end

   resources :projections do
     collection do
       get "with_stats/:sport_name" => 'projections#with_stats'
       get "stats_by_game/:sport_name" => 'projections#stats_by_game', :as => :stats_by_game
       get ":sport_name" => 'projections#index' # funky, index has a parameter? does this work?
     end
     resources :projection_by_stats do
       resources :projection_by_stat_and_games do
         resources :projection_breakdowns
       end
     end
   end

  resources :password_resets

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/lineup.rb
# == Schema Information
#
# Table name: lineups
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  sport      :string(255)
#

class Lineup < ActiveRecord::Base
  has_many :entries, inverse_of: :lineup
  has_many :lineup_spots, inverse_of: :lineup, dependent: :destroy
  has_many :players, through: :lineup_spots
  belongs_to :user, inverse_of: :lineups

  before_save :mark_unused_spot_for_removal

  accepts_nested_attributes_for :lineup_spots, allow_destroy: true

  #virtual attribute: enter a contest immediately after creation
  attr_accessor :contest_id_to_enter

  validate :salary_cap_validate
  validate :sport_positions_validate

  def salary_cap_validate
    #errors.add(:sport, "bogus error")
  end

  def sport_positions_validate
    #errors.add(:sport, "bogus error2")

  end

  # NILS: BUGBUG: Remove this?
  def completed?
    entries[0].present? && entries[0].contest.complete?
  end

  class << self
    def build_for_contest(contest, lineup = nil)
      # create empty LineupSpots and a Lineup object for a new lineup.
      lineup = Lineup.find_by_id(lineup) || Lineup.new
      lineup.sport = contest.sport
      lineup.contest_id_to_enter = contest.id

      LineupSpotProto.where(sport: contest.sport).order(spot: :asc).each do |proto|
        if lineup.lineup_spots.find_by_spot(proto.spot).blank?
          lineup.lineup_spots.build sport_position: SportPosition.find_by_sport_and_name(proto.sport, proto.sport_position_name), spot: proto.spot
        end
      end

      lineup
    end

  end

  protected
  def mark_unused_spot_for_removal
    lineup_spots.each do |spot|
      spot.mark_for_destruction if spot.player.blank?
    end
  end
end

app/controllers/lineups_controller.rb
class LineupsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_lineup, only: [:edit, :update]

  def new
    @contest = Contest.includes(:eligible_players).find(params[:contest_id])
    @lineup  = Lineup.build_for_contest @contest
    populate_lineup_variables @lineup.sport
  end

  def edit
    @contest = @lineup.entries[0].contest
    @positions = SportPosition.where(sport: @lineup.sport, visible: true).order(display_priority: :asc)
    populate_lineup_variables @lineup.sport
    render action: 'new'

  end

  def result

  end

  def create
    # this is the POST request for creating a new lineup.
    contest_id = params[:lineup][:contest_id_to_enter]
    sport = params[:lineup][:sport]
    @lineup = current_user.lineups.new(lineup_parameters)
    # Create an entry that new lineup belongs to. Exception if user has too many entries in contest
    if @lineup.valid?
      begin
        @entry = Contest.find(@lineup.contest_id_to_enter).enter(@lineup) if @lineup.contest_id_to_enter.present?
      rescue RuntimeError, ActiveRecord::RecordInvalid => e
        redirect_to "/", alert: e.message
        return
      end
    end

    if @entry.nil? or !@lineup.valid?
      # error path
      @contest = Contest.includes(:eligible_players).find(contest_id)
      populate_lineup_variables sport
      flash.now[:alert] = @lineup.errors.full_messages.join ", "
      render action: 'new'
      return
    end

    # success path
    respond_to do |format|
      format.html { redirect_to entries_path, notice: "Congratulations. You have entered the contest." }
      format.json { render action: 'show', status: :created, location: @lineup }
    end
  end

  # PATCH /entries
  # PATCH /entries.json
  def update 
    #@lineup.contest = @contest ## Nils: This causes a bug, maybe it's outdated code?

    respond_to do |format|
      if @lineup.update(lineup_parameters)
        format.html { redirect_to lineups_path, notice: 'Lineup was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @lineup }
      else
        @positions = @contest.sport_positions.includes(:players).order(display_priority: :asc)
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end


  def index
    @lineups = current_user.lineups.includes([:lineup_spots]).order(updated_at: :desc).limit 3
  end

  def export
    render layout: false
  end

  private
  def set_lineup
    @lineup = Lineup.find(params[:id])
  end

  def lineup_parameters
    params.require(:lineup).permit(:contest_id_to_enter, :sport, lineup_spots_attributes: [:player_id, :id, :sport_position_id, :spot])
  end

  def populate_lineup_variables sport
    # fill out all the fields the lineup page (new / create / edit needs)
    @positions = SportPosition.where(sport: sport, visible: true).order(display_priority: :asc)
    # BUGBUG: definitely duplication here between positions and sportpositions
    @sportpositions = SportPosition.all
    @teams = Team.all
    @players = @contest.eligible_players.with_summary_fppg
    # select fields we want to display, making sure FPPG field is added.
    @players = @players.select('players.id', 'sport_position_id', 'salary', 'first_name',
                               'last_name', 'stat_value AS fppg', 'ext_player_id', 'team_id')
    @games = GameScore.where({playdate: @contest.contestdate})  # BUGBUG: is this used?

  end


end

app/helpers/lineups_helper.rb
module LineupsHelper
  def collection_for_sports_options
    Contest.group(:sport).pluck(:sport).map do |sport|
      [sport, sport]
    end
  end

  def consumed_salary(lineup)
    lineup.players.sum(:salary)
  end

end

app/views/lineups/_draft_team.html.erb
<!-- <div class='jumbotron team teamDraft'>
  <div class='contestlive'>
    <strong> Contest Live In</strong>
    <%= countdown_tag @contest.start_at %>
  </div>
  <h1>Draft Your Team</h1>

  <p>
    Choose from the available players below, and submit your team.
    <br/>
    You can edit your team at any time until the game starts.
  </p>

  <p>
    <strong class='green'>Full Contest Rules & Prizes »</strong>
  </p>

  <h1 class="bold"><%= @contest.sport %></h1>
  <h4>(Mon-Thurs) [5 step 1 Tix Gtd.]</h4>

  <h1 class='bold'> <%= number_to_currency @contest.prizepool, precision: 0 %> Prize Pool</h1>
</div>

<p class='timingschedule'>
  <strong>Start Time:</strong>
  October 14,2013 at 8:40pm EST
  <strong>Entry Fee:</strong>
  <%= contest_entry_fee @contest %>
  <strong>Entries:</strong>
  <span class='green'>564/Uni »</span>
</p>

<div class='welcomeNote'>SELECT THE BEST TEAM WITHOUT EXCEEDING THE SALARY CAP.</div> -->
<div class='row drafting-info-row'>
  <div class='col-md-3'>
    <div class='row drafting-change-padding'>
      <div class='col-xs-6 first'>
        <h3 class='text-right'>NBA</h3>
      </div>
      <div class='col-xs-6 second'>
        <h6>50/50</h6>
        <p class="small-margin-top"><strong>12-31-2014</strong></p>
      </div>
    </div>
  </div>
  <div class='col-md-5'>
    <div class='row hidden-xs hidden-sm drafting-change-padding'>
      <div class='col-xs-3 first'>
        <h3 class='text-right'>$9</h3>
      </div>
      <div class='col-xs-9 second'>
        <h6>PRIZE POOL</h6>
        <p class="small-margin-top">Entry fee: <strong>$1</strong> Entries: <strong class='drafting-entries-border'>15/100</strong></p>
      </div>
    </div>
    <div class='row hidden-md hidden-lg drafting-change-padding'>
      <div class='col-xs-6 first'>
        <h3 class='text-right'>$9</h3>
      </div>
      <div class='col-xs-6 second'>
        <h6>PRIZE POOL</h6>
        <p class="small-margin-top">Entry fee: <strong>$1</strong> Entries: <strong>15/100</strong></p>
      </div>
    </div>
  </div>
  <div class='col-md-4'>
    <div class='row hidden-xs hidden-sm drafting-time-section'>
      <div class='col-xs-4 first'>
        <p class='live-border'>LIVE</p>
      </div>
      <div class='col-xs-2 second'>
        <p class='contest-prefix'>in</p>
      </div>
      <div class='col-xs-6 third'>
        <h3>4:12:24</h3>
        <p class='contest-time'>8:40pm EST</p>
      </div>
    </div>
    <div class='row hidden-md hidden-lg'>
      <div class='col-xs-6'>
        <h3 class='text-right'>LIVE in</h3>
      </div>
      <div class='col-xs-6'>
        <h3 class='text-left'>4:12:24</h3>
        <p class='contest-time'>8:40pm EST</p>
      </div>
    </div>
  </div>
</div>
<div class='row drafting-header-row'>
  <div class='col-md-12 text-center'>
    <h1>DRAFT YOUR TEAM</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,</p>
    <p> sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.</p>
    <p><a href='#'>Full contest rules and prizes &gt;&gt;</a></p>
  </div>  
</div>



<div class='col-md2 '>
  <h2 class='drafting-subheader-bold'>AVAILABLE PLAYERS</h2>
  <ul class='dropdownsport'>
    <li>
      <div class='styled-select'>

        <%= select :filter, :player, options_for_select(collection_for_sports_options), {include_blank: "ALL GAMES"} %>

      </div>
    </li>
    <li>
      <input placeholder="Search" type="text" id="js-draft-search">
    </li>
  </ul>

  <ul id='filterSport' class='nav nav-tabs'>
    <li class="active">
      <a href="#ALL">ALL</a>
    </li>
    <% @positions.each do |position| %>
        <li>
          <%= link_to position.name, "##{position.name} " %>
        </li>
    <% end %>
  </ul>
  
  <div class="js-draft-emitter">
    <table class="tab lineup table striped-grid no-margin-bottom">
      <thead>
        <tr>
          <th class="position">POS</th>
          <th class="player">PLAYER</th>
          <th class="opp">OPP</th>
          <th class="salary">SALARY</th>
          <th class="ffpg">FPPG</th>
          <th class="add">&nbsp;</th>
          <th class="scroll-dist">&nbsp;</th>
        </tr>
      </thead>
    </table>
  </div>

  <!-- render drafting table body with all players -->

  <div class="tab-content same-height js-draft-receiver padding-right">
    <div class='tab-pane active' id="ALL">
      <table class='tab lineup table sortable striped-grid'>
        <thead class="hide">
        <tr>
          <th class="position">POS</th>
          <th data-defaultsort="asc" class="player">PLAYER</th>
          <th class="opp">OPP</th>
          <th class="salary" data-defaultsort="desc">SALARY</th>
          <th class="ffpg">FPPG</th>
          <th class="add">&nbsp;</th> 
          <th class="scroll-dist">&nbsp;</th>
        </tr>
        </thead>
        <tbody id="lineup-eligible-players-el">
          <!-- filled in via bootstrap -->
          <!-- < render partial: 'lineups/lineup_player', collection: @contest.eligible_players, as: :player %> -->
        </tbody>
      </table>
    </div>

  </div>
  <p class='green'>Export to CSV »</p>
</div>
<!-- right half of screen - chosen lineup -->
<%= form_for @lineup do |f| %>
    <div class='col-md2'>
      <h2 class='drafting-subheader-bold'>LINEUP</h2>

      <div class='col-lg-6'>
        <h4>
          <strong> AVG. REM./PLAYER:</strong>
          <span id='avg-rem-salary' class="currency">
            <%= number_to_currency consumed_salary(@lineup), precision: 0 %>
          </span>
        </h4>
      </div>
      <div class='col-lg-6'>
        <h4 class="salary-wrapper">
          <strong> REM./SALARY:</strong>
          <span id='contest-salary-cap' class="currency" data-salary=<%= @contest.salary_cap %>>
             <%= number_to_currency @contest.salary_cap - consumed_salary(@lineup), precision: 0 %>
          </span>
        </h4>
      </div>
      <div class="lineups-push-block"></div>
      <!-- render chosen lineup -->

      <table class='tab same-height striped-grid'>
        <thead>
        <tr>
          <th>POS</th>
          <th>PLAYER</th>
          <th>OPP</th>
          <th>SALARY</th>
          <th>FPPG</th>
          <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <%= f.fields_for :lineup_spots do |spot_form| %>
            <% spot = spot_form.object %>
            <% position = spot.sport_position %>
            <%= content_tag :tr, id: dom_id(spot), class: 'lineup-spot', data: {sport_position_name: position.name, player_id: spot.player_id, spot: spot.spot} do %>
              <td class="position">
                <strong><span><%= position.name %> </span></strong>
                <%= spot_form.hidden_field :sport_position_id %>
                <%= spot_form.hidden_field :spot %>
              </td>
              <td class='player val player-stats'>
                <span class="player-link"></span>
                <%= spot_form.hidden_field :player_id %>
              </td>
              <td class='opp val'>
                <span>&nbsp;</span>
              </td>
              <td class='salary val'>
                <span class="currency">&nbsp;</span>
              </td>
              <td class='fppg val'>
                <span>&nbsp;</span>
              </td>
              <td class='action-icon'><%= link_to 'x', '#_', class: 'remove-from-lineup', data: {lineup_spot: spot.spot} %> </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
      <%= link_to 'Import »', '#_', class: 'green', id: 'import-lineups' %>
      <%= link_to 'Clear »', '#_', class: 'green', id: 'clear-lineups' %>
    </div>

    <%= f.hidden_field :sport %>
    <%= f.hidden_field :contest_id_to_enter %>
    <div class='clear'> &nbsp;</div>
    <div class='submitTeam'>
      <%= f.submit 'SUBMIT TEAM', disable_with: 'Please wait...' %>
    </div>
<% end %>

app/views/lineups/_lineup.html.erb
<div class="lineup-wrapper col-md-4">
  <!-- line below had lineup.completed? in place of 'false' -->

  <div class="gridbox <%= false ? "complete" : "upcoming" %>">
    <!---Box Header-->
    <header>
      <div class="pull-left">
        <%= image_tag "sports/#{lineup.sport.downcase}.png" %>
        <strong><%= lineup.sport %></strong></div>
      <div class="pull-right">
        <!-- line below had lineup.completed? in place of 'false' -->

        <% if false  %>
            <strong>COMPLETE</strong>
        <% elsif lineup.entries.empty? %>
            <strong>NEW</strong>
          <% else %>
            <strong>UPCOMING</strong>: <%= countdown_tag lineup.entries[0].contest.start_at %>
        <% end %>
      </div>
    </header>
    <ul class="summary">
      <li># of Entries</li>
      <li>PMR</li>
      <li>REM.Salary</li>
    </ul>
    <ul class="summary green">
      <li>1</li>
      <li>540</li>
      <li>$0</li>
    </ul>
    <!---/Box Header-->
    <table class="tab lineup">
      <thead>
      <tr>
        <th>POS</th>
        <th>PLAYER</th>
        <th>FPPG</th>
      </tr>
      </thead>
      <tbody>
      <% lineup.lineup_spots.each do |lineup_spot| %>
          <tr>
            <td><span><strong><%= lineup_spot.sport_position.name %></strong></span></td>
            <td data-stats-url="<%= stats_player_path(lineup_spot.player) if lineup_spot.player %>" class="<%= 'player-stats' if lineup_spot.player %>"><span class="green"><%= lineup_spot.player.try(:name) || "&nbsp;".html_safe %></span></td>

            <td><span><%= (lineup_spot.player ? "24.5" : "&nbsp;").html_safe %></span></td>
          </tr>
      <% end %>
      <tr>
        <!-- line below had lineup.completed? in place of 'false' -->
        <td colspan="4" style="color: white; text-align: center;"><%= (false ? "<strong>FANTASY POINTS</strong>: 126.7" : "&nbsp;").html_safe %></td>
      </tr>
      </tbody>
    </table>
    <p class="last-edit small"><strong>Last Edit:</strong> <%= lineup.updated_at.strftime "%b %d %Y %I:%M %p %Z" %></p>
    <footer>
      <ul>
        <!-- line below had lineup.completed? in place of 'false' -->

        <% unless false %>
          <li><span class="green"><%= link_to "Edit »", edit_lineup_path(lineup) %></span></li>
          <li><span class="green"><a data-stats-url="/lineups/<%= lineup.id %>/export" href="javascript:void(0);" class="lineup-export">Export »</a></span></li>
        <% end %>
        <li><span class="green"><a href="/entries">Entries »</a></span></li>
        <% unless lineup %>
          <li><span class="green"><a href="#">Challenge »</a></span></li>
          <li><span class="green"><%= link_to 'Submit »', lineup_entries_path(lineup), method: :post %></span></li>
        <% end %>
      </ul>
    </footer>
  </div>
</div>

app/views/lineups/_lineup_player.html.erb
<%= content_tag :tr, id: dom_id(player), class: 'contest-player', data: {player_id: player.id, player_name: player.name, player_salary: player.salary, player_opp: 'Ind@SDD', player_fppg: 24.5, player_position: player.sport_position.name} do %>
    <td class="position">
      <span>
        <strong> <%= player.sport_position.name %> </strong>
      </span>
    </td>
    <td class='player player-stats' data-stats-url="<%= stats_player_path player %>">
      <span class='player-link'><%= player.name %> </span>
    </td>
    <td class='opp'>
      <span>Ind@<strong class='home-team'>SDD</strong></span>
    </td>
    <td class='salary currency'>
      <span data-salary=<%= player.salary %>> <%= number_to_currency player.salary, precision: 0 %></span>
    </td>
    <td class='fppg'>
      <span>24.5</span>
    </td>
    <td class='action-icon'><%= link_to '+', '#_', class: 'add-to-lineup' %> </td>
<% end %>

app/views/lineups/export.erb
<div class="capitalcontent">
    <div class="capitalpopup">
      <div class="popupTitle">
        <h2 class="message"></h2>
        <button type="button" class="btnClose" data-dismiss="modal">X</button>
      </div>
      <div class="popupSubTitle">
      	<h3>Enter this lineup into other contests:</h3>
      </div>

      <div class="contests-container">
      	<table class="contests">
      		<thead>
      			<tr>
	      			<th>GAME</th>
	      			<th>ENTRIES</th>
	      			<th>ENTRY</th>
	      			<th>PRIZES</th>
	      			<th>&nbsp;</th>
	      		</tr>
      		</thead>
      		<tbody>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      		</tbody>
      	</table>
      </div>

      <div class="actions-container">
      	<a href="#" data-dismiss="modal" class="green no-thanks">No thanks, go to my lineup »</a>
      	<div class="clear"></div>
      </div>
    </div>
</div>

app/views/lineups/export.html.erb
<div class="capitalcontent">
    <div class="capitalpopup">
      <div class="popupTitle">
        <h2 class="message"></h2>
        <button type="button" class="btnClose" data-dismiss="modal">X</button>
      </div>
      <div class="popupSubTitle">
      	<h3>Enter this lineup into other contests:</h3>
      </div>

      <div class="contests-container">
      	<table class="contests">
      		<thead>
      			<tr>
	      			<th>GAME</th>
	      			<th>ENTRIES</th>
	      			<th>ENTRY</th>
	      			<th>PRIZES</th>
	      			<th>&nbsp;</th>
	      		</tr>
      		</thead>
      		<tbody>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      			<tr>
      				<td>Daily NBA Freeroll(10*$300K NFL Bomb Entries)</td>
      				<td>560</td>
      				<td>$3</td>
      				<td>$560,00,00</td>
      				<td><a href="#" class="table-btn">Enter</a></td>
      			</tr>
      		</tbody>
      	</table>
      </div>

      <div class="actions-container">
      	<a href="#" data-dismiss="modal" class="green no-thanks">No thanks, go to my lineup »</a>
      	<div class="clear"></div>
      </div>
    </div>
</div>