config/routes.rb
require "resque_web"

Main::Application.routes.draw do

  
  
  ActiveAdmin.routes(self)
  
  
  ResqueWeb::Engine.eager_load!

  mount ResqueWeb::Engine => "/resque_web"

  get "users/leadboard"
  get "users/signin_popup"

  get "splash/index", as: :splash
  root to: "contests#browse"

  get "terms/", :controller => "terms", :action => "index"
  get "privacy-policy/", :controller => "privacy_policy", :action => "index"

  devise_for :users, :controllers => {:sessions => 'sessions', :registrations => 'registrations' }

  get '/users/subregion_options' => 'users#subregion_options'
  resources :pages do
    collection do
      get :rules_faq
    end
  end
  resources :entries do
    member do
        post 'admin'
    end
  end

  scope(:path => 'admin', :as => 'admin') do
    get 'games', to: 'admin#games'
    get 'entries', to: 'admin#entries'
    get 'contests', to: 'admin#contests'
    get 'users', to: 'admin#users'
    get "/", to: "admin#index"
  end

  resources :lineups do
    member do
      get :export
    end
    resource :entries
  end
  resources :players, only: [] do
    member do
      get :stats
    end
  end
  resources :contests, only: [:index, :show] do
    collection do
      get 'browse'
    end
  end

  resources :waiting_lists, only: [:new, :create, :show] do
    collection do
      get :invite
      post :inviting
    end
  end

  resources :accounts, only: [:create, :edit, :show, :index] do
    collection do
      get :new_cc
      get :profile
      get :history
      get :withdraw
      get :add_fund

      resources :credit_cards
      post 'credit_cards/deposit' => 'credit_cards#deposit'

      get 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal', :as => :withdrawal
      post 'bank_accounts/withdrawal' => 'bank_accounts#withdrawal_post'
      resources :bank_accounts
    end
  end

   resources :projections do
     collection do
       get "with_stats/:sport_name" => 'projections#with_stats'
       get "stats_by_game/:sport_name" => 'projections#stats_by_game', :as => :stats_by_game
       get ":sport_name" => 'projections#index' # funky, index has a parameter? does this work?
     end
     resources :projection_by_stats do
       resources :projection_by_stat_and_games do
         resources :projection_breakdowns
       end
     end
   end

  resources :password_resets

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/projection_by_stat_and_games_controller.rb
class ProjectionByStatAndGamesController < ApplicationController
  before_action :set_projection_by_stat

  # GET /projection_by_stat_and_games
  def index
    @projection_by_stat_and_games = @projection_by_stat.proj_by_stat_crit
  end

  private
    def set_projection_by_stat
      @projection_by_stat = Projection::ProjectionByStat.find(params[:projection_by_stat_id])
    end
end

app/helpers/projection_by_stat_and_games_helper.rb
module ProjectionByStatAndGamesHelper
end

app/views/projection_by_stat_and_games/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to @projection_by_stat.projection.player.name, projection_projection_by_stats_path(@projection_by_stat.projection) %></a></li>
  <li><%= link_to @projection_by_stat.stat_name, projection_projection_by_stat_projection_by_stat_and_games_path(@projection_by_stat.projection, @projection_by_stat) %></a></li>
</ol>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Stat</th>
      <th>Projection</th>
      <th>Projection(weighted)</th>
    </tr>
  </thead>

  <tbody>
    <% @projection_by_stat_and_games.each do |pbsg| %>
      <tr>
        <td><%= pbsg.criteria %></td>
        <td><%= link_to pbsg.fp.to_s, projection_projection_by_stat_projection_by_stat_and_game_projection_breakdowns_path(pbsg.projection_by_stat.projection, pbsg.projection_by_stat, pbsg) %></td>
        <td><%= pbsg.weighted_fp %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>